import React from 'react'
import Layout from '../Layouts/Layout'

const About = () => {
  return (
    <Layout>
      <h1 className='my-9 justify-center text-center font-bold	text-4xl font-serif	'>Welcome to my Restuarant</h1>
      <p className='text-justify	drop-shadow-2xl	'>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Mollitia necessitatibus excepturi officiis, hic deserunt laboriosam qui maiores amet pariatur exercitationem distinctio veritatis omnis id impedit quod incidunt enim voluptatibus perferendis placeat dolor repellendus minus natus. Enim, consequatur nesciunt, nihil voluptatum sapiente itaque sed officia modi suscipit ad officiis cum odit ipsum voluptate expedita natus dicta, perferendis deleniti accusantium? Cumque vero eos, ab earum delectus a quae vitae dolore aperiam quam incidunt aliquid in laborum modi ea culpa aliquam iusto exercitationem quos fugit, numquam itaque? Voluptatibus pariatur molestias obcaecati recusandae amet quos vitae porro veniam tempore? Mollitia enim sunt magni numquam.</p>
      <br />
      <p className='text-justify 	drop-shadow-2xl	'>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Blanditiis sequi provident voluptatibus voluptate labore eveniet, accusamus at quo est inventore. Ipsam voluptates, similique soluta iusto ipsa sed praesentium delectus sit. Ad ut, non suscipit sapiente doloremque obcaecati et, necessitatibus ipsam similique dicta quo asperiores? Repellat quam accusamus atque fuga corporis vel, rem corrupti, at voluptas cumque consectetur officia. Dolorem, voluptatibus cum iure iusto consectetur sunt! Sint tempore iure, illum et nisi ipsa facere blanditiis nobis deleniti, accusantium ipsum tempora nemo neque? Sequi modi eum quibusdam tenetur, molestias eos aliquam amet perspiciatis vel. Maiores, quas accusantium delectus nemo unde asperiores repellendus!</p>
      <br/>
      <p className='text-justify	drop-shadow-2xl	'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus eum ipsa exercitationem laudantium quos nostrum possimus, et numquam earum assumenda quod, explicabo distinctio delectus in autem consectetur molestias qui! Perspiciatis autem accusamus distinctio, ducimus expedita, eos commodi ullam deleniti odit ipsum nihil consequatur voluptatibus. Adipisci dolor reprehenderit minima ipsum, itaque asperiores dolore dolores ea, maiores dicta quaerat magnam optio officia. Voluptatibus delectus incidunt eaque quidem eius quod illo, odit aut aperiam expedita! Repellendus, nisi odit nostrum velit aspernatur repudiandae totam quae eius blanditiis! Deleniti nostrum fugiat optio obcaecati enim cumque! Voluptatibus, repellat perferendis incidunt neque repudiandae nulla eum facilis ut!</p>
      <br/>
      <p className='text-justify	drop-shadow-2xl	'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Id officiis veritatis, ab quod, error eligendi inventore totam in iste debitis ad sit quibusdam minima? Velit, fuga consectetur at ex illum excepturi officia rerum mollitia fugiat doloremque repellat. Aliquam, repudiandae incidunt tenetur, dolorem minus quibusdam similique assumenda repellendus laborum, alias quasi! Voluptatum repellat alias repudiandae sint itaque quisquam officiis ipsam soluta, non id. Adipisci, eaque reprehenderit quidem neque dolore possimus assumenda vero nulla explicabo aut eum debitis incidunt maiores maxime placeat, iusto enim recusandae sed cum commodi harum. Dignissimos aliquam itaque ipsam earum nostrum placeat animi tenetur totam tempore ea. Nostrum, ex aliquam! Temporibus et deleniti ab iure fugit provident molestiae tenetur praesentium quibusdam ullam. Consectetur quo possimus sapiente deserunt, neque doloribus, exercitationem similique vero debitis esse deleniti reiciendis explicabo nam laboriosam eligendi corrupti delectus provident, quasi inventore tempore ea officiis consequuntur. Possimus distinctio ab a, odit magnam veritatis ea dignissimos.</p>   
    </Layout>
  )
}

export default About
